[build]
  command = "pip install -r requirements.txt && python build.py"
  publish = "static" # This tells Netlify where your static files are

[functions]
  directory = "netlify/functions"
  external_node_modules = [] # We're using Python, not Node.js functions
  python_version = "3.9" # Or your preferred Python version that Netlify supports

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200