# netlify.toml

[build]
  # No build step needed, since we are serving plain HTML/CSS/JS
  # If you had a bundler (e.g. Webpack), you'd put that command here.
  command = "echo 'No build required for static site.'"

  # Publish directory must point to the 'static' folder
  publish = "static"

  # If you decide later to add Netlify Functions (JS), you can uncomment:
  # functions = "netlify/functions"
  
[dev]
  # Allow Netlify Dev to proxy API calls to local FastAPI if you run it locally
  command = "netlify dev"
  port = 8888
